### PR TITLE
Connor's Awesomeness

### PR DESCRIPTION
**Pull request by connor557**

### CODE REVIEW

**Comment by joshiggins** [comment]
Hi Connor

This looks good, but the reason you had some problems with APT errors is because the packages are installed by https://github.com/kxes/platform-client 

In short, you register configuration "channels" that will match to the system and provide configuration information like which packages should be installed. The idea is you can make sure the state of all managed systems remains consistent.

So if you look at https://github.com/kxes/config-productivity-apps/blob/master/productivity.json for example, you could add a block in the JSON like this

```
"thunderbirdpackage" : {
                "provider": "apt",
                "task": "install",
                "package": "thunderbird"
            }
```

and then in the Dockerfile register the repo as a channel like this

```
RUN platform-client --addchannel https://github.com/kxes/config-productivity-apps.git
```

I wrote platform-client because I wanted something like Puppet and Chef but without needing to run a server. This was an experiment to use the same configuration that I use for desktop PCs to make a virtual desktop in a container. Doing it this way using platform-client means I can reuse the same configuration for real machines as well as virtual ones instead of rewriting everything in Dockerfiles.

**Comment by joshiggins** [comment]
Of course you could create a separate git repo with the config for xfce4-goodies, firefox, thunderbird and pidgin in.

You'd need a file named Configfile

```
[Configuration]
Name=connors-desktop
Description=Install goodies
Author=your name here
Enabled=goodies

[goodies]
Scope=system
System=Linux
Distname=Ubuntu,Debian
```

and then a JSON file called goodies.json

```
{
    "updatecache": {
        "provider": "apt",
        "task": "update",
        "on_success": {
            "xfce4-goodies" : {
                "provider": "apt",
                "task": "install",
                "package": "xfce4-goodies"
            },
            "firefox" : {
                "provider": "apt",
                "task": "install",
                "package": "firefox"
            },
            "thunderbird" : {
                "provider": "apt",
                "task": "install",
                "package": "thunderbird"
            },
            "pidgin" : {
                "provider": "apt",
                "task": "install",
                "package": "pidgin"
            }
        }
    }
}
```

push those to a repo and add it to the Dockerfile after the kxdesktop channel

```
RUN platform-client --addchannel https://github.com/your/new/repo.git
```

**Comment by connor557** [comment]
Do you have any other ideas on packages I should add? Btw, I have a running installation of this if you want to check it out. connorsite.com:3389 root account and password is still Docker with capital D. Probbly should change that. :)

**Comment by connor557** [comment]
I stopped using this system last week because I thought it was not flexible enough. I started using Cendio ThinLinc for the gateway with Docker as the VM provider.

**Comment by joshiggins** [comment]
Fair doos. If you want something that works out of the box then a turn key solution like ThinLinc might do the job. If you like hacking, then nothing is more flexible than doing it yourself :)

**Pull request closed without merging**
